# Remote Functions

BigQuery DataFrames (a.k.a. BigFrames) can facilitate deploying Python functions
to Cloud Run and registering them as BigQuery Remote Functions. This enables
your Python to be used from the scalable BigQuery query engine from Python and
SQL.

In [1]:
# Select a GCP project where you have query user permissions.
PROJECT_ID = "bigframes-dev"  # @param {type: "string"}

In [2]:
import datetime

# BigQuery table data on which notebook should be run
TABLE='bigquery-public-data.stackoverflow.comments'

# Change this up to test the scale, down to run the notebook faster
START_DATE = datetime.datetime(2018, 10, 4, tzinfo=datetime.timezone.utc)
END_DATE = datetime.datetime(2018, 10, 9, tzinfo=datetime.timezone.utc)

In [3]:
##############################
#       Pandas World         #
##############################

import pandas_gbq
df = pandas_gbq.read_gbq(
    f"""
    SELECT id, text, score
    FROM {TABLE}
    WHERE creation_date BETWEEN '{START_DATE.isoformat()}' AND '{END_DATE.isoformat()}'
    """,
    project_id=PROJECT_ID,
)
df

Downloading: 100%|██████████|

              id                                               text  score
0      125639963  After trying many suggestions from various sit...      0
1       96118456  There is a question regarding Spring Boot and ...      0
2       96925761  switching from https to http doesn't work as a...      0
3       95857775  I have faced the same issue but fixed using wi...      0
4       95866320  It would appear that the service being connect...      0
...          ...                                                ...    ...
92559   92225718  You are creating an independent application in...      4
92560   92241966  What do you mean *'showing dd/mm/yyyy format'*...      4
92561   92287261  Why are you using `FromCollection` instead of ...      4
92562   92294962  What is this thing called `Range`? It's certai...      4
92563   92348649  Posting on stackoverflow should be done *after...      4

[92564 rows x 3 columns]

In [4]:
# User defined function
# https://www.codespeedy.com/find-nth-prime-number-in-python/
def nth_prime(n: int) -> int:
    prime_numbers = [2,3]
    i=3
    if(0<n<=2):
        return prime_numbers[n-1]
    elif(n>2):
        while (True):
            i+=1
            status = True
            for j in range(2,int(i/2)+1):
                if(i%j==0):
                    status = False
                    break
            if(status==True):
                prime_numbers.append(i)
            if(len(prime_numbers)==n):
                break
        return prime_numbers[n-1]
    else:
        return -1

In [5]:
df = df.assign(n_prime=df['score'].apply(nth_prime))
df.head(10)

,id,text,score,n_prime
0,125639963,After trying many suggestions from various sit...,0,-1
1,96118456,There is a question regarding Spring Boot and ...,0,-1
2,96925761,switching from https to http doesn't work as a...,0,-1
3,95857775,I have faced the same issue but fixed using wi...,0,-1
4,95866320,It would appear that the service being connect...,0,-1
5,100197459,Here is a your project with small changes here...,0,-1
6,100197460,Thanks. I'll take a look and see if it works.,0,-1
7,100197461,Ok. So I've pulled your project down and updat...,0,-1
8,100197462,"ok, because in my case I didnt need to use pg ...",0,-1
9,100197463,I got sqlite3 working and I'm still getting th...,0,-1

In [6]:
##############################
#     BigQuery DataFrames     #
##############################

import bigframes.pandas as bpd

# Use partial ordering mode for the best BigQuery performance.
bpd.options.bigquery.ordering_mode = "partial"
bpd.options.bigquery.project = PROJECT_ID

df = bpd.read_gbq(TABLE)
filter_col = (
    (START_DATE <= df["creation_date"]) & (df["creation_date"] <= END_DATE)
)
df = df[filter_col][['id', 'text', 'score']]
df.peek()

          id                                               text  score
0  125639963  After trying many suggestions from various sit...      0
1   92211453  I/O is slow, potentially blocking and a good c...      6
2   92211586             That is not an array. It is an object.      8
3   92211889  This command closes all the buffers. How can I...      6
4   92212245  I think this is a valid question. As I read it...      7

In [7]:
# You can check that this DataFrame is the same size as in the pandas example.
df.shape

(92564, 3)

In [8]:
# Tell the user what needs to be done offline before using BigQuery DataFrame
# remote functions
help(bpd.deploy_remote_function)

Help on function deploy_remote_function in module bigframes.pandas:

deploy_remote_function(func, **kwargs)
    Orchestrates the creation of a BigQuery remote function that deploys immediately.

    This method ensures that the remote function is created and available for
    use in BigQuery as soon as this call is made.

    Args:
        func:
            Function to deploy.
        kwargs:
            All arguments are passed directly to
            :meth:`~bigframes.session.Session.remote_function`.  Please see
            its docstring for parameter details.

    Returns:
        A wrapped remote function, usable in
        :meth:`~bigframes.series.Series.apply`.

In [9]:
nth_prime_bigframes = bpd.deploy_remote_function(
    nth_prime,
    # For the best isolation, use a custom service account for Cloud Run.
    # Choosing "default" uses the default GCE service account, which may have
    # more permissions than you want.
    cloud_function_service_account="default",
)

In [10]:
# Let's apply the function to the dataframe
df = df.assign(n_prime=df['score'].apply(nth_prime_bigframes))
df.peek()

         id                                               text  score  n_prime
0  92211453  I/O is slow, potentially blocking and a good c...      6       13
1  92211586             That is not an array. It is an object.      8       19
2  92211889  This command closes all the buffers. How can I...      6       13
3  92212245  I think this is a valid question. As I read it...      7       17
4  92212453  a BufferedInputStream has an *internal* buffer...      6       13

In [11]:
# We can see the path to the BQ remote function and the google cloud function
# that was created under the hood
print(nth_prime_bigframes.bigframes_remote_function)
print(nth_prime_bigframes.bigframes_cloud_function)

bigframes-dev._63cfa399614a54153cc386c27d6c0c6fdb249f9e.bigframes_session83c930_cc017726
projects/bigframes-dev/locations/us-central1/functions/bigframes-session83c930-5984f70d

In [12]:
# Let's try to simulate a scenario in which user shares this remote function to
# their colleague who simply wants to reuse it. BigFrames provides an API to do
# so via `read_gbq_function`. Usage details are available via `help` command.
help(bpd.read_gbq_function)

Help on function read_gbq_function in module bigframes.pandas.io.api:

read_gbq_function(function_name: str, is_row_processor: bool = False)
    Loads a BigQuery function from BigQuery.

    Then it can be applied to a DataFrame or Series.

    .. note::
        The return type of the function must be explicitly specified in the
        function's original definition even if not otherwise required.

    BigQuery Utils provides many public functions under the ``bqutil`` project on Google Cloud Platform project
    (See: https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs#using-the-udfs).
    You can checkout Community UDFs to use community-contributed functions.
    (See: https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/community#community-udfs).

    **Examples:**

    Use the [cw_lower_case_ascii_only](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/README.md#cw_lower_case_ascii_onlystr-string)
    function from Community UDFs.

        >>> import bigframes.pandas as bpd
        >>> func = bpd.read_gbq_function("bqutil.fn.cw_lower_case_ascii_only")

    You can run it on scalar input. Usually you would do so to verify that
    it works as expected before applying to all values in a Series.

        >>> func('AURÉLIE')
        'aurÉlie'

    You can apply it to a BigQuery DataFrames Series.

        >>> df = bpd.DataFrame({'id': [1, 2, 3], 'name': ['AURÉLIE', 'CÉLESTINE', 'DAPHNÉ']})
        >>> df
           id       name
        0   1    AURÉLIE
        1   2  CÉLESTINE
        2   3     DAPHNÉ
        <BLANKLINE>
        [3 rows x 2 columns]

        >>> df1 = df.assign(new_name=df['name'].apply(func))
        >>> df1
           id       name   new_name
        0   1    AURÉLIE    aurÉlie
        1   2  CÉLESTINE  cÉlestine
        2   3     DAPHNÉ     daphnÉ
        <BLANKLINE>
        [3 rows x 3 columns]

    You can even use a function with multiple inputs. For example,
    [cw_regexp_replace_5](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/master/udfs/community/README.md#cw_regexp_replace_5haystack-string-regexp-string-replacement-string-offset-int64-occurrence-int64)
    from Community UDFs.

        >>> func = bpd.read_gbq_function("bqutil.fn.cw_regexp_replace_5")
        >>> func('TestStr123456', 'Str', 'Cad$', 1, 1)
        'TestCad$123456'

        >>> df = bpd.DataFrame({
        ...     "haystack" : ["TestStr123456", "TestStr123456Str", "TestStr123456Str"],
        ...     "regexp" : ["Str", "Str", "Str"],
        ...     "replacement" : ["Cad$", "Cad$", "Cad$"],
        ...     "offset" : [1, 1, 1],
        ...     "occurrence" : [1, 2, 1]
        ... })
        >>> df
                   haystack regexp replacement  offset  occurrence
        0     TestStr123456    Str        Cad$       1           1
        1  TestStr123456Str    Str        Cad$       1           2
        2  TestStr123456Str    Str        Cad$       1           1
        <BLANKLINE>
        [3 rows x 5 columns]
        >>> df.apply(func, axis=1)
        0       TestCad$123456
        1    TestStr123456Cad$
        2    TestCad$123456Str
        dtype: string

    Another use case is to define your own remote function and use it later.
    For example, define the remote function:

        >>> @bpd.remote_function(cloud_function_service_account="default")  # doctest: +SKIP
        ... def tenfold(num: int) -> float:
        ...     return num * 10

    Then, read back the deployed BQ remote function:

        >>> tenfold_ref = bpd.read_gbq_function(  # doctest: +SKIP
        ...     tenfold.bigframes_remote_function,
        ... )

        >>> df = bpd.DataFrame({'a': [1, 2], 'b': [3, 4], 'c': [5, 6]})
        >>> df
            a   b   c
        0   1   3   5
        1   2   4   6
        <BLANKLINE>
        [2 rows x 3 columns]

        >>> df['a'].apply(tenfold_ref)  # doctest: +SKIP
        0    10.0
        1    20.0
        Name: a, dtype: Float64

    It also supports row processing by using `is_row_processor=True`. Please
    note, row processor implies that the function has only one input
    parameter.

        >>> @bpd.remote_function(cloud_function_service_account="default")  # doctest: +SKIP
        ... def row_sum(s: pd.Series) -> float:
        ...     return s['a'] + s['b'] + s['c']

        >>> row_sum_ref = bpd.read_gbq_function(  # doctest: +SKIP
        ...     row_sum.bigframes_remote_function,
        ...     is_row_processor=True,
        ... )

        >>> df = bpd.DataFrame({'a': [1, 2], 'b': [3, 4], 'c': [5, 6]})
        >>> df
            a   b   c
        0   1   3   5
        1   2   4   6
        <BLANKLINE>
        [2 rows x 3 columns]

        >>> df.apply(row_sum_ref, axis=1)  # doctest: +SKIP
        0     9.0
        1    12.0
        dtype: Float64

    Args:
        function_name (str):
            The function's name in BigQuery in the format
            `project_id.dataset_id.function_name`, or
            `dataset_id.function_name` to load from the default project, or
            `function_name` to load from the default project and the dataset
            associated with the current session.
        is_row_processor (bool, default False):
            Whether the function is a row processor. This is set to True
            for a function which receives an entire row of a DataFrame as
            a pandas Series.

    Returns:
        collections.abc.Callable:
            A function object pointing to the BigQuery function read
            from BigQuery.

            The object is similar to the one created by the `remote_function`
            decorator, including the `bigframes_remote_function` property, but
            not including the `bigframes_cloud_function` property.

In [13]:
EXISTING_REMOTE_FUNCTION=nth_prime_bigframes.bigframes_remote_function

# Let's read the existing remote function in bigframes
nth_prime_existing = bpd.read_gbq_function(EXISTING_REMOTE_FUNCTION)

In [14]:
%%time

# Let's apply the existing function to the dataframe
df = df.assign(n_prime_again=df['score'].apply(nth_prime_existing))
df.peek()

CPU times: user 31.2 ms, sys: 292 μs, total: 31.5 ms
Wall time: 1.65 s

,id,text,score,n_prime,n_prime_again
0,92207417,Short answer is you cannot - your view has `@m...,0,-1,-1
1,92207459,"Just a tip bro , when using VM use a real devi...",0,-1,-1
2,92207565,Thanks Patrick I tried something similar like ...,0,-1,-1
3,92207681,Without a [mcve] (lacking the entity and archi...,0,-1,-1
4,92207703,Its just a workaround. It doesnt have to be do...,0,-1,-1

In [15]:
# Clean up GCP assets created as part of bigframes remote_function
def cleanup_remote_function_assets(remote_udf, ignore_failures=False):
    """Clean up the GCP assets behind a bigframes remote function."""

    session = bpd.get_global_session()

    # Clean up BQ remote function
    try:
        session.bqclient.delete_routine(remote_udf.bigframes_remote_function)
    except Exception:
        # By default don't raise exception in cleanup
        if not ignore_failures:
            raise

    # Clean up cloud function
    try:
        session.cloudfunctionsclient.delete_function(name=remote_udf.bigframes_cloud_function)
    except Exception:
        # By default don't raise exception in cleanup
        if not ignore_failures:
            raise

cleanup_remote_function_assets(nth_prime_bigframes)